### ISSUE TITLE
CityBattle System

### ISSUE THREAD

**Issue by Collines** [Collines/Venoxis-BugTracker#13]
As the title says it will be an event at which Alliance will attack Horde's main city and Horde will attack Alliance city, it will last for 1 hour or so, the faction that'll capture the flag will get MG, Honor, Arena and more loot chance.

- [x] Scripting the system
- [x] Scripting the Objects

**Comment by sundayz** [comment]
Fully implemented the manager class and helper functions, just needs small changes.
