### ISSUE TITLE
relogging while mounted

### ISSUE THREAD

**Issue by stinkyjoint** [Collines/Venoxis-BugTracker#15]
i was mounted when i logged off, when i logged back in i have the mount buff but no mount
and my run speed is the same as if i am mounted and i can go in combat also and keep the buff how ever going inside a building removes the mount effect

**Comment by sundayz** [comment]
@Collines It sounds like this is a visual issue. Can you confirm that this happens? It could be because the mount model id hasn't yet loaded (slow RAM or hdd). If you wait long enough, it should load.

**Comment by stinkyjoint** [comment]
100% not just visual... I did one of the whole quests with mount speed  fighting

**Comment by Collines** [comment]
Fixed

**Comment by sundayz** [comment]
Re-open if issue persists.
