### ISSUE TITLE
Mission VIII Gem Gameobject

### ISSUE THREAD

**Issue by sundayz** [Collines/Venoxis-BugTracker#2]
Excerpt from Discord chat.

> [5:40 PM] ⚕⚚☤Yes☤⚚⚕: The gem for Mission VIII is only clickable once. Aka if you click it before you get the quest, you can click it when youre on the quest.
> [5:41 PM] ⚕⚚☤Yes☤⚚⚕: This is propably server-side, which means that only one person on the server can click it per restart

**Comment by Insaniuz** [comment]
This has been fixed.
