### ISSUE TITLE
Warlock's bug, and some other stuff.

### ISSUE THREAD

**Issue by Srdgodx** [Collines/Venoxis-BugTracker#23]
Aight, so i've been leveling a warlock. but realized something odd about 10 mins in. My conflagerate sucks, it literally does 108 dmg crit and 44 damage over-time. i do think this is pretty dumb and should be buffed.

Unstoppable Affliction: It does really low damage.

Warlock T1-T2 gear lacks spell power. this is a major disadvantage. sure intellect is cool but we require more then just mana x)

I'll report more stuff asap.

Regards. Hyperstate.

**Comment by sundayz** [comment]
@Insaniuz Is this fixed? Reopen until confirmed.
