### ISSUE TITLE
Some bugs i found

### ISSUE THREAD

**Issue by Srdgodx** [Collines/Venoxis-BugTracker#25]
Druid:  Don't have Bear form, either can train maul. since both of em requires a quest complete.

Warriors: At the starting quest charge is bugged, you cannot use it. which leads to that you cannot complete your journey on the leveling section.

**Comment by Collines** [comment]
Druid missing spells are fixed.

**Comment by Srdgodx** [comment]
Note: the warrior thing was just about the guy being uncunning. he didnt know you had to be in Battle Stance to use it. tried it and it works.
