### ISSUE TITLE
Deadmines

### ISSUE THREAD

**Issue by Srdgodx** [Collines/Venoxis-BugTracker#29]
Idunno if its suppose to be that way, but the quest in the start to bring 5 mine carts to the guy doesnt work. i try bringing them to him they just dissappear when i get close and it doenst count. so it's still 0/5. on top of that idunno about the boss but i think the first boss (Soulseeker) is bugged. cause you cannot attack him.

**Comment by sundayz** [comment]
Please provide steps on how to reproduce this issue. Get everyone to leave the instance and reset it. Re-open this issue if it happens again. The first boss unlocks once all mine carts are returned.
