### ISSUE TITLE
The Real Trial (Horde)

### ISSUE THREAD

**Issue by Blyatman1** [Collines/Venoxis-BugTracker#30]
As a Hunter, once you start combat against the Orgrimmar Grunt NPC for the quest "The Real Trial", if you Feign Death, the NPC will stop attacking you, allowing you to attack the NPC without it attacking back, thus allowing you to finish the encounter with ease.

**Comment by sundayz** [comment]
Orgrimmar Grunt will now ignore Feign Death and Vanish-like effects.

Thanks for the report.
